resources:
- name: fhir_apis
  type: solutions.api
  properties:
    inputs:
    - name: org
      prompt: Edge Org name
    - name: username
      prompt: Edge Username
      ifNotPresent: token
    - name: password
      prompt: Edge Password
      ifNotPresent: token
    - name: env
      prompt: Edge Org Environment
    - name: target_server_host
      prompt: Target server host URL
    - name: target_server_port
      prompt: Target server port
      default: 80
    - name: target_server_basepath
      prompt: Target server basepath
    - name: usergrid_org
      prompt: BaaS Org name
    - name: usergrid_app
      prompt: BaaS App name
    - name: usergrid_client_id
      prompt: BaaS Org Client Id
    - name: usergrid_secret
      prompt: BaaS Org Client Secret
    configurations:
    - env: test
      baas_host: https://apibaas-trial.apigee.net
      edge_host: https://api.enterprise.apigee.com
      host: '{{ org }}-{{ env }}.apigee.net'
    - env : prod
      baas_host: https://apibaas-trial.apigee.net
      edge_host: https://api.enterprise.apigee.com
      host: '{{ org }}-{{ env }}.apigee.net'

    edgeOrg:
    script: gulpfile.js
    basePath: .
    dependencies:
    subResources:
    - name: target_server
      type: targetServer
      items:
      - name: target_server_1
        payload: '{ "host": "{{ target_server_host }}","isEnabled": true,"name": "fhirserver","port": "{{ target_server_port }}"}'

    - name: replace_variables_fhir
      type: configSubstitutions
      items:
      - name: connector_domain
        filePaths: ['src/gateway/fhir-api/target/apiproxy/policies/HPX_SetConnector.xml']
        value: '{{ org }}-{{ env }}.apigee.net'
      - name: connector_basepath
        filePaths: ['src/gateway/fhir-api/target/apiproxy/policies/HPX_SetConnector.xml']
        value: 'hapi-dstu2'
      - name: targetBaseURI
        filePaths: ['src/gateway/fhir-connector-hapi-dstu2/target/apiproxy/policies/HPX_SetTargetBasepath.xml']
        value: '{{ target_server_basepath }}'

    - name: insurance_proxies
      type: proxy
      items:
      - name: fhir-api
      - name: fhir-connector-hapi-dstu2
      - name: catch-all
      - name: oauth-b2b

    - name: developers
      type: developer
      items:
      - payload: '{"email":"testuser@apigee.com", "firstName":"test","lastName":"user","userName":"testuser"}'
        email: testuser@apigee.com
      - payload: '{"email":"user@identity.com", "firstName":"Identity","lastName":"User","userName":"iuser"}'
        email: user@identity.com

    - name: apiProducts
      type: product
      items:
      - name: testFHIRproduct
        payload: '{"approvalType":"auto","attributes": [{"name": "RATE_LIMIT_OVERRIDE_LIMIT","value": "100ps"}],"displayName":"testFHIRproduct","name":"testFHIRproduct","environments":["{{ env }}"],"proxies": ["fhir-api"],"apiResources":["/","/**"],"quota": "10000", "quotaInterval": "1", "quotaTimeUnit": "minute","scopes" : ["patient/Allergyintolerance.read","patient/Allergyintolerance.write","patient/Careplan.read","patient/Careplan.write","patient/Condition.read","patient/Condition.write","patient/Diagnosticorder.read","patient/Diagnosticorder.write","patient/Diagnosticreport.read","patient/Diagnosticreport.write","patient/Documentreference.read","patient/Documentreference.write","patient/Encounter.read","patient/Encounter.write","patient/Immunization.read","patient/Immunization.write","patient/Medicationadministration.read","patient/Medicationadministration.write","patient/Medicationdispense.read","patient/Medicationdispense.write","patient/Medicationorder.read","patient/Medicationorder.write","patient/Medicationstatement.read","patient/Medicationstatement.write","patient/Observation.read","patient/Observation.write","patient/Patient.read","patient/Patient.write","patient/Practitioner.read","patient/Practitioner.write","patient/Procedure.read","patient/Procedure.write","user/Allergyintolerance.read","user/Allergyintolerance.write","user/Careplan.read","user/Careplan.write","user/Condition.read","user/Condition.write","user/Diagnosticorder.read","user/Diagnosticorder.write","user/Diagnosticreport.read","user/Diagnosticreport.write","user/Documentreference.read","user/Documentreference.write","user/Encounter.read","user/Encounter.write","user/Immunization.read","user/Immunization.write","user/Medicationadministration.read","user/Medicationadministration.write","user/Medicationdispense.read","user/Medicationdispense.write","user/Medicationorder.read","user/Medicationorder.write","user/Medicationstatement.read","user/Medicationstatement.write","user/Observation.read","user/Observation.write","user/Patient.read","user/Patient.write","user/Practitioner.read","user/Practitioner.write","user/Procedure.read","user/Procedure.write","patient/Schedule.read","patient/Schedule.write","user/Schedule.read","user/Schedule.write","patient/Coverage.read","patient/Coverage.write","user/Coverage.read","user/Coverage.write"]}'
      - name: identityproduct
        payload: '{"approvalType":"auto","attributes": [{"name": "RATE_LIMIT_OVERRIDE_LIMIT","value": "100ps"}],"displayName":"Identity App Product","name":"identityproduct","environments":["{{ env }}"], "quota": "100", "quotaInterval": "1", "quotaTimeUnit": "minute","scopes" :["patient/Allergyintolerance.read","patient/Allergyintolerance.write","patient/Careplan.read","patient/Careplan.write","patient/Condition.read","patient/Condition.write","patient/Diagnosticorder.read","patient/Diagnosticorder.write","patient/Diagnosticreport.read","patient/Diagnosticreport.write","patient/Documentreference.read","patient/Documentreference.write","patient/Encounter.read","patient/Encounter.write","patient/Immunization.read","patient/Immunization.write","patient/Medicationadministration.read","patient/Medicationadministration.write","patient/Medicationdispense.read","patient/Medicationdispense.write","patient/Medicationorder.read","patient/Medicationorder.write","patient/Medicationstatement.read","patient/Medicationstatement.write","patient/Observation.read","patient/Observation.write","patient/Patient.read","patient/Patient.write","patient/Practitioner.read","patient/Practitioner.write","patient/Procedure.read","patient/Procedure.write","patient/Schedule.read","patient/Schedule.write","patient/Coverage.read","patient/Coverage.write"]}'

    - name: developerApps
      type: app
      items:
      - name: testFHIRApp
        payload: '{"name":"testFHIRApp","callback":"https://{{ org }}-{{ env }}.apigee.net","email":"testuser@apigee.com","apiProducts":"testFHIRproduct"}'
      - name: IdentityApp
        payload: '{"name":"IdentityApp", "callback":"https://{{ org }}-{{ env }}.apigee.net/identity_app/callback","email":"user@identity.com","apiProducts":"identityproduct"}'
        assignResponse:
        - from: credentials.0.consumerKey
          to: apiKey_identity
        - from: credentials.0.consumerSecret
          to: apiSecret_identity

    - name: cacheResources
      type: cache
      items:
      - name: consent-session-cache
        payload: '{ "name": "consent-session-cache"}'
      - name: application-session-cache
        payload: '{ "name": "auth-req-param-cache"}'
      - name: sms-token-cache
        payload: '{ "name": "session-cookie-cache"}'
      - name: nonce-cache
        payload: '{ "name": "nonce-cache"}'

    - name: create_baas_app
      type: baasApp
      items:
      - appName: '{{ usergrid_app }}'

    - name: get_baas_app_cred
      type: getBaasAppCredential
      items:
      - appName: '{{ usergrid_app }}'
        assignResponse:
        - from: credentials.client_id
          to: baas_client_id
        - from: credentials.client_secret
          to: baas_secret

    - name: generate_auth
      type: util
      items:
      - action: base64.encode
        value: '{{ baas_client_id }}:{{ baas_secret }}'
        assignTo: baas_auth

    - name: replace_variables_consent_app
      type: configSubstitutions
      items:
      - name: consent_app_RedirectToConsent
        filePaths: ['src/gateway/identity-consent-app/target/apiproxy/policies/HPX_redirectToConsent.xml']
        value: 'https://{{ org }}-{{ env }}.apigee.net/openid/index?sessionid={sessionid}'
      - name: AssignSendSMSAPIRequest_apikey
        filePaths: ['src/gateway/identity-consent-app/target/apiproxy/policies/HPX_AssignSendSMSAPIRequest.xml']
        value: '{{ usergrid_client_id }}'
      - name: logoutRedircetUri
        filePaths: ['src/gateway/identity-consent-app/target/apiproxy/policies/HPX_AssignlogoutRedircetUri.xml']
        value: 'https://{{ org }}-{{ env }}.apigee.net/openid/index'
      - name: hostName
        filePaths: ['src/gateway/identity-consent-app/target/apiproxy/policies/HPX_AddVariablesToTargetRequest.xml']
        value: 'https://{{ org }}-{{ env }}.apigee.net'
      - name: baas_auth
        filePaths: ['src/gateway/identity-consent-app/target/apiproxy/policies/HPX_CheckAlreadyConsented.ServiceCallout.xml','src/gateway/identity-consent-app/target/apiproxy/policies/HPX_GetUserApps.ServiceCallout.xml','src/gateway/identity-consent-app/target/apiproxy/policies/HPX_RevokeUserConsent.ServiceCallout.xml','src/gateway/identity-consent-app/target/apiproxy/policies/HPX_ValidatePin.ServiceCallout.xml']
        value: 'ClientCredential {{ baas_auth }}'
      - name: HPX_CheckAlreadyConsented_url
        filePaths: ['src/gateway/identity-consent-app/target/apiproxy/policies/HPX_CheckAlreadyConsented.ServiceCallout.xml']
        value: 'https://{{ org }}-{{ env }}.apigee.net/identity/consents/validate'
      - name: CheckMSISDNExists_url
        filePaths: ['src/gateway/identity-consent-app/target/apiproxy/policies/HPX_CheckMSISDNExists.ServiceCallout.xml']
        value: 'https://{{ org }}-{{ env }}.apigee.net/identity-users/v1/users/{msisdn}'
      - name: HPX_CheckUserExists_url
        filePaths: ['src/gateway/identity-consent-app/target/apiproxy/policies/HPX_CheckUserExists.ServiceCallout.xml']
        value: 'https://{{ org }}-{{ env }}.apigee.net/identity-users/v1/users/{username}'
      - name: HPX_CreateUser_url
        filePaths: ['src/gateway/identity-consent-app/target/apiproxy/policies/HPX_CreateUser.ServiceCallout.xml']
        value: 'https://{{ org }}-{{ env }}.apigee.net/identity-users/v1/users'
      - name: HPX_GenerateAuthCode_url
        filePaths: ['src/gateway/identity-consent-app/target/apiproxy/policies/HPX_GenerateAuthCode.Callout.xml']
        value: 'https://{{ org }}-{{ env }}.apigee.net/oauth/v2/code'
      - name: HPX_GetUserApps_url
        filePaths: ['src/gateway/identity-consent-app/target/apiproxy/policies/HPX_GetUserApps.ServiceCallout.xml']
        value: 'https://{{ org }}-{{ env }}.apigee.net/identity/consents'
      - name: HPX_GetUserProfileFromUserManagement_url
        filePaths: ['src/gateway/identity-consent-app/target/apiproxy/policies/HPX_GetUserProfileFromUserManagement.xml']
        value: 'https://{{ org }}-{{ env }}.apigee.net/identity-users/v1/users/{userid}'
      - name: HPX_ResetPassword_url
        filePaths: ['src/gateway/identity-consent-app/target/apiproxy/policies/HPX_ResetPassword.ServiceCallout.xml']
        value: 'https://{{ org }}-{{ env }}.apigee.net/identity-users/v1/users/{reset_username}/password'
      - name: HPX_RevokeUserConsent_url
        filePaths: ['src/gateway/identity-consent-app/target/apiproxy/policies/HPX_RevokeUserConsent.ServiceCallout.xml']
        value: 'https://{{ org }}-{{ env }}.apigee.net/identity/consents/{request.queryparam.consentid}'
      - name: HPX_SendSMS_url
        filePaths: ['src/gateway/identity-consent-app/target/apiproxy/policies/HPX_SendSMS.ServiceCallout.xml']
        value: 'https://{{ org }}-{{ env }}.apigee.net/v1/token/sms/{msisdn}'
      - name: HPX_ServiceCallout_IdentifyUser_url
        filePaths: ['src/gateway/identity-consent-app/target/apiproxy/policies/HPX_ServiceCallout.IdentifyUser.xml']
        value: 'https://{{ org }}-{{ env }}.apigee.net/authenticate/identify'
      - name: HPX_ServiceCallout_ValidateUser_url
        filePaths: ['src/gateway/identity-consent-app/target/apiproxy/policies/HPX_ServiceCallout.ValidateUser.xml']
        value: 'https://{{ org }}-{{ env }}.apigee.net/identity-users/v1/users/authenticate'
      - name: HPX_SetPassword_url
        filePaths: ['src/gateway/identity-consent-app/target/apiproxy/policies/HPX_SetPassword.ServiceCallout.xml']
        value: 'https://{{ org }}-{{ env }}.apigee.net/identity-users/v1/users/{username}/password'
      - name: HPX_UpdateUserProfile_url
        filePaths: ['src/gateway/identity-consent-app/target/apiproxy/policies/HPX_UpdateUserProfile.ServiceCallout.xml']
        value: 'https://{{ org }}-{{ env }}.apigee.net/identity-users/v1/users/{request.formparam.email}'
      - name: HPX_ValidatePin_url
        filePaths: ['src/gateway/identity-consent-app/target/apiproxy/policies/HPX_ValidatePin.ServiceCallout.xml']
        value: 'https://{{ org }}-{{ env }}.apigee.net/v1/token/sms/{msisdn}/{request.formparam.pin}'

    - name: replace_variables_identity_consent_mgnt_api
      type: configSubstitutions
      items:
      - name: baas_app
        filePaths: ['src/gateway/identity-consentmgmt-api/target/apiproxy/resources/node/package.json']
        value: '{{ usergrid_app }}'
      - name: baas_org
        filePaths: ['src/gateway/identity-consentmgmt-api/target/apiproxy/resources/node/package.json']
        value: '{{ usergrid_org }}'
      - name: HPX_DeleteExistingSimilarConsent_url
        filePaths: ['src/gateway/identity-consentmgmt-api/target/apiproxy/policies/HPX_DeleteExistingSimilarConsent.xml']
        value: 'https://api.usergrid.com/{{ usergrid_org }}/{{ usergrid_app }}/consents'
      - name: baas_client_id
        filePaths: ['src/gateway/identity-consentmgmt-api/target/apiproxy/policies/HPX_DeleteExistingSimilarConsent.xml','src/gateway/identity-consentmgmt-api/target/apiproxy/resources/node/package.json']
        value: '{{ usergrid_client_id }}'
      - name: baas_secret
        filePaths: ['src/gateway/identity-consentmgmt-api/target/apiproxy/policies/HPX_DeleteExistingSimilarConsent.xml','src/gateway/identity-consentmgmt-api/target/apiproxy/resources/node/package.json']
        value: '{{ usergrid_secret }}'

    - name: replace_variables_identity_usermgnt_api
      type: configSubstitutions
      items:
      - name: baas_app
        filePaths: ['src/gateway/identity-usermgmt-api/target/apiproxy/resources/node/package.json']
        value: '{{ usergrid_app }}'
      - name: baas_org
        filePaths: ['src/gateway/identity-usermgmt-api/target/apiproxy/resources/node/package.json']
        value: '{{ usergrid_org }}'
      - name: baas_client_id
        filePaths: ['src/gateway/identity-usermgmt-api/target/apiproxy/resources/node/package.json']
        value: '{{ usergrid_client_id }}'
      - name: baas_secret
        filePaths: ['src/gateway/identity-usermgmt-api/target/apiproxy/resources/node/package.json']
        value: '{{ usergrid_secret }}'

    - name: replace_variables_identity_oauthv2-api
      type: configSubstitutions
      items:
      - name: oauth_RedirectToConsent
        filePaths: ['src/gateway/identity-oauthv2-api/target/apiproxy/policies/HPX_redirectToConsent.xml']
        value: 'https://{{ org }}-{{ env }}.apigee.net/openid/onnet?sessionid={sessionid}'
      - name: HPX_GetUserProfileFromAppServices_url
        filePaths: ['src/gateway/identity-oauthv2-api/target/apiproxy/policies/HPX_GetUserProfileFromAppServices.xml']
        value: 'https://{{ org }}-{{ env }}.apigee.net/identity-users/v1/users/{accesstoken.userid}'
      - name: baas_auth
        filePaths: ['src/gateway/identity-oauthv2-api/target/apiproxy/policies/HPX_AssignStoreConsentRequest.xml']
        value: 'ClientCredential {{ baas_auth }}'
      - name: HPX_StoreConsent_url
        filePaths: ['src/gateway/identity-oauthv2-api/target/apiproxy/policies/HPX_StoreConsent.ServiceCallout.xml']
        value: 'https://{{ org }}-{{ env }}.apigee.net/identity/consents'
      - name: HPX_AssignIssuer
        filePaths: ['src/gateway/identity-oauthv2-api/target/apiproxy/policies/HPX_AssignIssuer.xml']
        value: 'https://{{ org }}-{{ env }}.apigee.net/'
      - name: HPX_CheckAlreadyConsented_url
        filePaths: ['src/gateway/identity-oauthv2-api/target/apiproxy/policies/HPX_CheckAlreadyConsented.ServiceCallout.xml']
        value: 'https://{{ org }}-{{ env }}.apigee.net/identity/consents/validate'

    - name: replace_variables_demo_app
      type: configSubstitutions
      items:
      - name: baas_client_id
        filePaths: ['src/gateway/identity-demo-app/target/apiproxy/policies/HPX_AddAuthorizationReqVarInReq.xml']
        value: '{{ usergrid_client_id }}'
      - name: demo_app_redirect_uri
        filePaths: ['src/gateway/identity-demo-app/target/apiproxy/policies/HPX_AddAuthorizationReqVarInReq.xml']
        value: 'https://{{ org }}-{{ env }}.apigee.net/identity_app/callback'
      - name: demo_app_authorization_req_url
        filePaths: ['src/gateway/identity-demo-app/target/apiproxy/policies/HPX_AddAuthorizationReqVarInReq.xml']
        value: '{{ https://{{ org }}-{{ env }}.apigee.net/oauth/v2/authorize }}'
      - name: HPX_GetAccessToken_url
        filePaths: ['src/gateway/identity-demo-app/target/apiproxy/policies/HPX_GetAccessToken_ServiceCallout.xml']
        value: 'https://{{ org }}-{{ env }}.apigee.net/oauth/v2/accesstoken'
      - name: HPX_GetUserDetails_url
        filePaths: ['src/gateway/identity-demo-app/target/apiproxy/policies/HPX_GetUserDetails_ServiceCallout.xml']
        value: 'https://{{ org }}-{{ env }}.apigee.net/oauth/v2/getdetails'
      - name: HPX_ReadPatient_url
        filePaths: ['src/gateway/identity-demo-app/target/apiproxy/policies/HPX_ReadPatient_Service-Callout.xml']
        value: 'https://{{ org }}-{{ env }}.apigee.net/fhir/v1/Patient'
      - name: HPX_ReadEncounterById_url
        filePaths: ['src/gateway/identity-demo-app/target/apiproxy/policies/HPX_ReadEncounterById_ServiceCallout.xml']
        value: 'https://{{ org }}-{{ env }}.apigee.net/fhir/v1/Encounter'
      - name: HPX_ReadPatientEncounterDetails_url
        filePaths: ['src/gateway/identity-demo-app/target/apiproxy/policies/HPX_ReadPatientEncounterDetails_ServiceCallout.xml']
        value: 'https://{{ org }}-{{ env }}.apigee.net/fhir/v1/Encounter'

    - name: identity_proxies
      type: proxy
      items:
      - name: identity-usermgmt-api
      - name: identity-consentmgmt-api
      - name: identity-sms-token-api
      - name: identity-consent-app
      - name: identity-oauthv2-api
      - name: identity-authentication-spi
      - name: identity-demo-app
